import { MOONS } from "./mock-moons";
import { Planet } from "./planet";

export const PLANETS: Planet[] = [
    { id: 1, 
        name: "Sonne", 
        diameter: 1392700, 
        url: "../assets/sonne.png",
    },
    { id: 2, 
        name: "Merkur", 
        diameter: 4879.4, 
        url: "../assets/Merkur.jpg" },
    { id: 3, 
        name: "Venus", 
        diameter: 12104, 
        url: "../assets/Venus.jpg" },
    { id: 4, 
        name: "Erde", 
        diameter: 12742, 
        url: "../assets/erde.png" ,
        moons: [MOONS[0]] },
    { id: 5, 
        name: "Mars", 
        diameter: 6779, 
        url: "..assets/mars.jpg" },
    { id: 6, 
        name: "Jupiter", 
        diameter: 139820, 
        url: "../assets/jupiter.jpg" },
    { id: 7, 
        name: "Saturn", 
        diameter: 116460, 
        url: "../assets/saturn.jpg" },
    { id: 8, 
        name: "Uranus", 
        diameter: 50724, 
        url: "../assets/uranus.png" },
    { id: 9, 
        name: "Neptun", 
        diameter: 499244, 
        url: "../assets/neptun.png" },
]